-- Schema used by the challenge (EMPLOYEE, DEPARTMENT, PAYMENTS).
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID   INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMP_ID     INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(50) NOT NULL,
    DOB        DATE NOT NULL,
    GENDER     VARCHAR(10),
    DEPARTMENT INT NOT NULL REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID   INT PRIMARY KEY,
    EMP_ID       INT NOT NULL REFERENCES EMPLOYEE (EMP_ID),
    AMOUNT       DECIMAL(10, 2) NOT NULL,
    PAYMENT_TIME TIMESTAMP NOT NULL
);
